workspace = { members = ["server"] }

[package]
name = "lb-2"
version = "0.1.0"
edition = "2021"


[dependencies]
axum = "0.7.4"
tokio = { version = "1.36.0", features = ["full"] }
hyper-util = { version = "0.1.3", features = [
    "client-legacy",
    "http1",
    "http2",
] }
